services:
  guide-browser:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./all_phenos:/app/all_phenos:ro
      - ./guide_all_100lat_bl_ll:/app/guide_all_100lat_bl_ll:ro
      - ./log10pvalues.npy:/app/log10pvalues.npy:ro
      - ./w_values:/app/w_values:ro
      # - ./betas.npy:/app/betas.npy:ro
